In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sk
import seaborn as snb

In [2]:
d=pd.read_csv('seeds.csv')

In [3]:
d.head()

Area  Perimeter  Compactness  Kernel.Length  Kernel.Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry.Coeff  Kernel.Groove  Type  
0            2.221          5.220     1  
1            1.018          4.956     1  
2            2.699          4.825     1  
3            2.259          4.805     1  
4            1.355          5.175     1

In [4]:
d.isnull().sum()

Area               0
Perimeter          0
Compactness        0
Kernel.Length      0
Kernel.Width       0
Asymmetry.Coeff    0
Kernel.Groove      0
Type               0
dtype: int64

In [5]:
d.columns=['Area', 'Perimeter', 'Compactness', 'Kernel_Length','Kernel_Width', 'Asymmetry_Coeff','Kernel_Groove' , 'Category']



In [6]:
d.head()

Area  Perimeter  Compactness  Kernel_Length  Kernel_Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry_Coeff  Kernel_Groove  Category  
0            2.221          5.220         1  
1            1.018          4.956         1  
2            2.699          4.825         1  
3            2.259          4.805         1  
4            1.355          5.175         1

In [8]:
#Data Transformation
d["Category"].replace({1 :"Kama" , 2 :"Rosa" , 3 :"Canadian"} , inplace = True)
d.head()

Area  Perimeter  Compactness  Kernel_Length  Kernel_Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry_Coeff  Kernel_Groove Category  
0            2.221          5.220     Kama  
1            1.018          4.956     Kama  
2            2.699          4.825     Kama  
3            2.259          4.805     Kama  
4            1.355          5.175     Kama

In [12]:
x = d.iloc[:, 0:7]
x.head()

Area  Perimeter  Compactness  Kernel_Length  Kernel_Width  \
0  15.26      14.84       0.8710          5.763         3.312   
1  14.88      14.57       0.8811          5.554         3.333   
2  14.29      14.09       0.9050          5.291         3.337   
3  13.84      13.94       0.8955          5.324         3.379   
4  16.14      14.99       0.9034          5.658         3.562   

   Asymmetry_Coeff  Kernel_Groove  
0            2.221          5.220  
1            1.018          4.956  
2            2.699          4.825  
3            2.259          4.805  
4            1.355          5.175

In [14]:
y=d['Category']

In [15]:
y.head()

0    Kama
1    Kama
2    Kama
3    Kama
4    Kama
Name: Category, dtype: object

In [16]:
from sklearn.model_selection import train_test_split


In [17]:
x_train , x_test , y_train , y_test = train_test_split(x, y, random_state=50, test_size = 0.25)


In [18]:
from sklearn.naive_bayes import GaussianNB

#Create a Gaussian Classifier
model = GaussianNB()

# Train the model using traning sets
model.fit(x_train, y_train)

# Predict the response for test datasets
Y_pred = model.predict(x_test)

In [19]:
import sklearn.metrics as metrics


In [22]:
print("accuracy:", metrics.accuracy_score (y_test, Y_pred)*100)


accuracy: 86.0


In [24]:
data=[[14.26,14.84,0.9710,4.763,3.212,3.221,4.220]]
model.predict(data)

C:\Users\Sai\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:409: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array(['Kama'], dtype='<U8')

In [23]:

test_pred = model.predict(x_test)

print(metrics.classification_report(y_test, test_pred))
print(metrics.confusion_matrix(y_test, test_pred))

              precision    recall  f1-score   support

    Canadian       1.00      0.75      0.86        20
        Kama       0.72      0.87      0.79        15
        Rosa       0.88      1.00      0.94        15

    accuracy                           0.86        50
   macro avg       0.87      0.87      0.86        50
weighted avg       0.88      0.86      0.86        50

[[15  5  0]
 [ 0 13  2]
 [ 0  0 15]]
